version: '3.8'

networks:
  selenoid-network:
    name: selenoid-network

services:
  selenoid:
    image: aerokube/selenoid:latest
    networks:
      - selenoid-network
    volumes:
      - ./config:/etc/selenoid
      - /var/run/docker.sock:/var/run/docker.sock
      - ./video:/opt/selenoid/video
      - ./logs:/opt/selenoid/logs
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/opt/selenoid/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "selenoid-network"]
    ports:
      - "4444:4444"

  selenoid-ui:
    image: aerokube/selenoid-ui:latest
    networks:
      - selenoid-network
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
    depends_on:
      - selenoid